### ISSUE TITLE
Roblox crashing

### ISSUE THREAD

**Issue by ShashTheEpic** [L8X/Roblox-Client-Optimizer#104]
After using this, Roblox randomly crashes randomly for me with the last frame being frozen. I can't close it manually by clicking on the x icon, opening task manager and ending the task nor pressing alt + f4. I have to restart my laptop to make it stop using its resources.

**Comment by Kaiddd** [comment]
@ShashTheEpic this is Roblox, not RCO, the new byfron update is causing crashes.

https://youtu.be/TG1i1QB3O-U
