### ISSUE TITLE
Uninstalling

### ISSUE THREAD

**Issue by Sydneylikespancakes** [L8X/Roblox-Client-Optimizer#106]
When, I try to uninstall the program, it claims it has uninstsalled itself, but when I load back into a game, it is still in-effect, I have rebooted my computer multiple times, and would like to know if their is a explanation to this or not.

**Comment by Sydneylikespancakes** [comment]
This issue has been resolved.

**Comment by Kaiddd** [comment]
Uninstalling RCO uninstalls the program but not the flag list
