### ISSUE TITLE
Access to RCO2 denied

### ISSUE THREAD

**Issue by averagesleepenjoyer** [L8X/Roblox-Client-Optimizer#111]
<img width="335" alt="image" src="https://user-images.githubusercontent.com/131934880/234746368-5488d246-c0bb-448a-a158-52d0492fcbbc.png">
How do I fix this? This happened after I closed rco on the first day of usage (as I remember). While I'm here, do I need to install rco to open it everytime?

**Comment by Kaiddd** [comment]
Please install the new release.
