### ISSUE TITLE
Completely Makes My PC Unusable When Roblox is Launched

### ISSUE THREAD

**Issue by TERIHAX** [L8X/Roblox-Client-Optimizer#112]
I'm not sure how my problem can be reproduced, but when using RCO (enabled) and launching Roblox, my PC just completely lags out, all my things are delayed (like pressing the Win key would take like 30 seconds to open the start menu) and the PC just becomes completely unusable, I've had to force shutdown by pressing the power button on my PC multiple times.

This could be caused by some of the flags, I have no idea.

My PC specs are really bad but here it is:
Processor	Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz   3.50 GHz
Installed RAM	16.0 GB
System type	64-bit operating system, x64-based processor
Graphics Card: Nvidia Geforce GT 730 MSI

And my OS:
Edition	Windows 10 Pro N
Version	22H2
OS build	19045.2846
Experience	Windows Feature Experience Pack 120.2212.4190.0

**Comment by Kaiddd** [comment]
Please go through the json file and remove half of the flags and repeat the process till you find the flag that is causing any issues, and report the flag(s) back here

**Comment by TERIHAX** [comment]
How do I do that with RCO?

**Comment by Kaiddd** [comment]
Roblox-version-folder\ClientSettings\ClientAppSettings.json

**Comment by TERIHAX** [comment]
I've tried that, there isn't a clientsettings folder

**Comment by TERIHAX** [comment]
So I think the problem could be related to the "cache" fflags
