### ISSUE TITLE
RCO auto uninstall

### ISSUE THREAD

**Issue by Skelly00100** [L8X/Roblox-Client-Optimizer#120]
So, when i install it, and run Roblox. Roblox "updates" (basicly removes RCO). So it just says updating while it just deletes RCO and Roblox opens up. Is there any way running Roblox without getting RCO auto deleted?

**Comment by dobrin-glitch** [comment]
no, there isn't bc when Roblox does an update, they delete the old files and install the new "Roblox files" and rco is not a Roblox programm so u have to add it every update
