### ISSUE TITLE
Eset dedecting it as a virus and deletes it i know i can disable it but i dont trust it.

### ISSUE THREAD

**Issue by mtxontop** [L8X/Roblox-Client-Optimizer#123]
![resim_2023-04-27_204549759](https://user-images.githubusercontent.com/132004054/234948675-00491d7b-acf9-4093-955c-05e7bf38359e.png)
dont mind im turkish but it basically tells it is a virus and deleted

**Comment by Kaiddd** [comment]
Microsoft has confirmed RCO as safe, but if you still don't trust it feel free to read the source code and compile it yourself in visual studio 2022

Otherwise, not really our problem, feel free to report it as a false positive in eset
