### ISSUE TITLE
16-bit error when launching

### ISSUE THREAD

**Issue by tjblocks2912** [L8X/Roblox-Client-Optimizer#132]
The app was working fine until I got this error saying that my pc is not compatible with this app because it was "16-bit"
![16bit](https://user-images.githubusercontent.com/82232686/235312634-20d12326-6ff2-4711-9d45-23eb59ab4f9d.PNG)

**Comment by stan2474** [comment]
goddamn what r u guys building in @L8X, vs 1997?

**Comment by Kaiddd** [comment]
Use the latest installer on the latest release, old one has been broken for a while now

@stan2474 the old installer just downloads "Not found" or whatever

**Comment by tjblocks2912** [comment]
@Kaiddd thanks
