### ISSUE TITLE
Stupid but needed Linux support

### ISSUE THREAD

**Issue by Minepool9** [L8X/Roblox-Client-Optimizer#14]
Hi so i have been using this on windows a few days ago but recently changed to linux so i was wondering if you could add support to it on linux also note for linux people use a program called grape juice to install roblox i know you seem new to coding and this is a new program and again its random but i would like it if you added linux support

**Comment by Kaiddd** [comment]
I am not new to coding, only very lazy, and not amazing at c++, but due to roblox not having native Linux support, rco will not get support on linux at the moment, perhaps you could make a pull request if you know how it'd work, but I don't have any knowledge of grapejuice/wine to do it

**Comment by apprehensions** [comment]
@L8X, i would like to get your permission to use your FFlags files in my Roblox on Linux wrapper [vinegar](https://github.com/vinegar-dev/vinegar)?

**Comment by Kaiddd** [comment]
@apprehensions I am not l8x but I did also work on this project, you can wait for their response first if u want, but I do not mind, just leave l8x some credit

**Comment by he3als** [comment]
You can add it to Grapejuice by going to https://codebeautify.org/jsonviewer, pasting the JSON in, setting the tab space to 8 and then copy and pasting it under the `"fast_flags"` section of the Grapejuice config (`~/.config/brinkervii/grapejuice/user_settings.json`)

**Comment by apprehensions** [comment]
https://github.com/vinegar-dev/vinegar/blob/ea24469794fc627342ee36c44b86e52ecd02e1e2/README.md?plain=1#L10

Is this enough? i feel like it isn't.

**Comment by Minepool9** [comment]
> > I am not new to coding, only very lazy, and not amazing at c++, but due to roblox not having native Linux support, rco will not get support on linux at the moment, perhaps you could make a pull request if you know how it'd work, but I don't have any knowledge of grapejuice/wine to do it
> 
> @Minepool

> I am not new to coding, only very lazy, and not amazing at c++, but due to roblox not having native Linux support, rco will not get support on linux at the moment, perhaps you could make a pull request if you know how it'd work, but I don't have any knowledge of grapejuice/wine to do it

OH sorry i forgot about this comment i dont use git a lot

**Comment by Minepool9** [comment]
> https://github.com/vinegar-dev/vinegar/blob/ea24469794fc627342ee36c44b86e52ecd02e1e2/README.md?plain=1#L10
> 
> Is this enough? i feel like it isn't.

Thanks for showing me an alternative

**Comment by EasternBloxxer** [comment]
> @L8X, i would like to get your permission to use your FFlags files in my Roblox on Linux wrapper [vinegar](https://github.com/vinegar-dev/vinegar)?

You are better off without any flags. This most of the time makes the experience worse as they use some weird flags that arent even needed and dont optimize the client at all. For example the flag that enables VC to have a seperate log file.

**Comment by apprehensions** [comment]
> You are better off without any flags

free fps unlocker and performance so like

**Comment by Kaiddd** [comment]
Never getting linux support unless roblox adds native support for linux
