### ISSUE TITLE
16-bit application??

### ISSUE THREAD

**Issue by Corsaka** [L8X/Roblox-Client-Optimizer#148]
I downloaded the installer to my B: drive's downloads folder, attempted to run the installer, and got greeted by this error.

![image](https://user-images.githubusercontent.com/23699128/235388286-cbe16d91-e0d7-4858-b292-ebb0e1b0b2ab.png)

It does claim to have installed RCO, though I can't find it anywhere. I'm pretty sure I'm on version 2.0.6.

**Comment by Kaiddd** [comment]
That's the old installer please install the latest release
