### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by UnsightlyZazer** [L8X/Roblox-Client-Optimizer#20]
can someone pls tell me what i did wrong and how to fix it
![rco](https://user-images.githubusercontent.com/127027949/222960852-2024c6a5-dd8b-4d88-b247-a3d9c9dcf516.png)

**Comment by Kaiddd** [comment]
@UnsightlyZazer what you did wrong is a great question, what'd you do? Do you get that message after running the installer? Details? When does this error occur???

**Comment by Kaiddd** [comment]
Did any errors occur during installation?

**Comment by UnsightlyZazer** [comment]
it pops up after it says that it's done installing
![eeee](https://user-images.githubusercontent.com/127027949/222973467-ffed7d3f-ab7f-43aa-b00f-fa589e108fb9.png)

**Comment by UnsightlyZazer** [comment]
i uninstalled rco1 using the rco1 folder instead of uninstalling rco1 in the rco2 folder. maybe thats the part that i did wrong. hopefully that made sense lol

**Comment by UnsightlyZazer** [comment]
i just keep on reinstalling rco2 and restarting my pc but nothing seems to work

**Comment by Kaiddd** [comment]
@UnsightlyZazer it looks like the rco exe doesn't exist, you downloaded the release from the releases page right? You can't just download the .cmd file if that's what you did

**Comment by Kaiddd** [comment]
Also, did you unzip the zip file?

**Comment by UnsightlyZazer** [comment]
![release](https://user-images.githubusercontent.com/127027949/222974170-4f23f095-e684-4919-98fc-40ac0544bc9a.png)
i downloaded it from here and yes, i did extract it

**Comment by Kaiddd** [comment]
@UnsightlyZazer could you send a video of you installing rco from start to finish? Also, try running the uninstaller for rco2 before installing

**Comment by UnsightlyZazer** [comment]
https://user-images.githubusercontent.com/127027949/222993012-1e8519f8-4f35-4b98-ba86-0bb0d485fa3a.mp4

had to uninstall it twice just so i could see the error message

**Comment by Kaiddd** [comment]
@UnsightlyZazer I see, may be a windows 11 issue. Can you please open cmd to the folder and run the uninstaller through there, so that I can see error. If you need help with that please add Kaede#0666

**Comment by UnsightlyZazer** [comment]
sent

**Comment by Kaiddd** [comment]
Above issue was an issue with the users anti-virus, closing issue unless another problem arises.
