### ISSUE TITLE
[Bug] My character dies alone or bounces like crazy

### ISSUE THREAD

**Issue by Tembeyo** [L8X/Roblox-Client-Optimizer#24]
Hello, I found out that when I activate the program my character for some reason in some games flies when I get into **first person**, or in other cases when I move I lose life, and if I jump I die instantly.

I thought it was a typical Roblox bug, but after disabling the program, it turned out that the one with the error was the program.

If you need more information, I'll gladly give it to you and I'm sorry if you didn't understand some parts, since I used the translator xd.

**Comment by Kaiddd** [comment]
@Tembeyo Um, that's not possible, an fflag can't make you fly or lose health, and nobody else has reported this issue, but if you'd like please send me a recording as well as a game link that has the issue, until then I am closing this issue.

**Comment by Tembeyo** [comment]
Hello @Kaiddd and thanks for answering, I already prepared the video so that you can better see the problem I have [https://www.youtube.com/watch?v=481jYmKEHgE](url) while I explain what happens in the video so that there are no doubts.

1- At the beginning of the video I show you that the program is disabled, so the problem is not there.
2- After showing them that I had no problems, now I activate the program and the 2 problems that I had mentioned appear to me, the first in person and that I suffer damage out of nowhere for walking, (I suffer a lot of damage when I walk, it jumps xd).
3- And to make sure that it is yes or yes, I deactivate it again to verify that it is indeed the program that gives these problems.

(I hope the translator hasn't changed anything.)
