### ISSUE TITLE
roblox files location C:\Program Files (x86)

### ISSUE THREAD

**Issue by psycowrld** [L8X/Roblox-Client-Optimizer#25]
soo all of you can see I can't use your rco2gui because roblox decide to move roblox into program files (x86) soo your rco2gui tell me too reinstall or to delete but I already do it and nothing change so can all of you fix this

**Comment by Kaiddd** [comment]
@psycowrld stop running the Roblox installer as admin and it'll stop going to program files...

**Comment by psycowrld** [comment]
i never run my program into admin mode

**Comment by psycowrld** [comment]
actually i try run the installer roblox whitout admin still not working.

**Comment by psycowrld** [comment]
> @psycowrld programs are only able to physically install themselves to program files if they have admin perms...

how to disable admin right so?

**Comment by Kaiddd** [comment]
Make sure you uninstall the program files version first, and then install the regular roblox

**Comment by psycowrld** [comment]
ok thx did yu have discord or smth cause i need to talk directly to yu

**Comment by psycowrld** [comment]
oh hell nah still going to program files

**Comment by Kaiddd** [comment]
@psycowrld can you try to login to a non administrator user?

**Comment by Kaiddd** [comment]
Because honestly your PC being configured to allow files to be added to program files without admin, is much more concerning than Roblox installing to program files

**Comment by Kaiddd** [comment]
@psycowrld closing this, #28 
2.1.0 will support both of the Roblox install types.

**Comment by psycowrld** [comment]
> @psycowrld can you try to login to a non administrator user?

I tried and that's not worked, I think Roblox decided to move files into program files

**Comment by Kaiddd** [comment]
@psycowrld no, like I said before, you physically cannot put files into program files without administrative rights, your system is misconfigured. But like I said above, I'm adding program file support in 2.1.0

**Comment by Kaiddd** [comment]
#28, current estimate is unknown, but you can keep track at the just mentioned roadmap

**Comment by psycowrld** [comment]
i'm weating for 2.10 good work yall
