### ISSUE TITLE
Is there a case where FPS unlock fails?

### ISSUE THREAD

**Issue by apprehensions** [L8X/Roblox-Client-Optimizer#29]
Seeing the maintainers warn us about the FFlag `DFIntTaskSchedulerTargetFps` fail to unlock on certain systems, *when* exactly does this happen?

I'm mostly asking this, just to simply remove the need for rbxfpsunlocker in my Roblox wrapper.

**Comment by Kaiddd** [comment]
It'll only fail if Roblox ever removes the fflag in the future, unlikely, but possible (as far as I know)
