### ISSUE TITLE
GetHumanoidDescriptionFromUserId() (404)

### ISSUE THREAD

**Issue by ac-tu** [L8X/Roblox-Client-Optimizer#43]
We're back at it once again, it seems it has been reintroduced, I am unsure with what flag revision as I haven't played roblox in a couple days, but it's back to erroring.
![example 22](https://user-images.githubusercontent.com/76844190/231314225-4c0486ef-2510-4874-b504-521867c087d5.png)

**Comment by ac-tu** [comment]
I was also unsure how to reopen a closed issue, so apologies if this clogs it up a bit.

**Comment by ac-tu** [comment]
Flag seems to be ""FFlagClientAvatarUsesColor3sForBodyParts2" when set to "True", please keep this set to false from now on to resolve this  (unintentionally fixed with the [avatar inspection menu patch](https://github.com/L8X/Roblox-Client-Optimizer/commit/407cdea7e8743cc53c3ef803af4105f737d8f07f).)

**Comment by Kaiddd** [comment]
Buggy ass flag 💀 thanks for the report
