### ISSUE TITLE
I've reinstalled many times and this just keeps popping up.

### ISSUE THREAD

**Issue by yllmi** [L8X/Roblox-Client-Optimizer#47]
![image](https://user-images.githubusercontent.com/131224093/232952097-0b07526a-646d-4676-89a2-6c65645d2d40.png)

**Comment by Kaiddd** [comment]
Please verify if your 'Program Files (x86)' is set to 'Read-Only' and change it if so.

**Comment by yllmi** [comment]
I have deselected 'Read-Only', should I proceed with reinstalling roblox again?

**Comment by Kaiddd** [comment]
You want read only to be on, are you running the roblox installer as admin perhaps?

**Comment by yllmi** [comment]
How would I run without admin

**Comment by Kaiddd** [comment]
Please make sure you have UAC enabled

**Comment by yllmi** [comment]
Alright, I got it to work. Thank you very much for your help. :)

**Comment by Kaiddd** [comment]
Np :p
