### ISSUE TITLE
Network not found (potential bug, waiting for info)

### ISSUE THREAD

**Issue by Astrojox** [L8X/Roblox-Client-Optimizer#54]
I keep getting this bug report. Originally, I had one about an administrator...thing. My memory is pretty fuzzy.
![image](https://user-images.githubusercontent.com/111155678/233791342-0523501d-b76d-48d3-aa93-c24e9b832f46.png)

**Comment by Kaiddd** [comment]
@Astrojox this means there was a problem connecting to your internet, can you ensure your connection is stable, and then restart rco?

**Comment by Astrojox** [comment]
Alright, here's all the information I gathered:

- From the data I've collected, my internet is stable. However, I've been having router issues lately.
- My operating system is Windows 11, which may be causing the error.
- Initially, I had an administrative problem (more detail about this "bug" in Swooshified's post). I followed the directions and deleted Roblox's Version folder, causing 0xC.

**Comment by Astrojox** [comment]
Just successfully created a workaround! I added the .json file in the source code in Roblox's "ClientSettings" folder and everything is working smoothly.
Note: If you don't have the ClientSettings folder already, you can simply add it in and everything will still function properly.

**Comment by Kaiddd** [comment]
Now that you've gotten passed the admin issue, can you try to run the roblox installer again? See if rco program will work?
