### ISSUE TITLE
installing roblox without administrator 0xA

### ISSUE THREAD

**Issue by itsryp** [L8X/Roblox-Client-Optimizer#55]
![image](https://user-images.githubusercontent.com/124638749/233798113-96307e69-f551-4f0a-baa9-a93d816f8558.png)

**Comment by Kaiddd** [comment]
Did you uninstall roblox, delete it from program files, and reinstall it without admin, ensuring uac is turned on?

**Comment by itsryp** [comment]
> Did you uninstall roblox, delete it from program files, and reinstall it without admin, ensuring uac is turned on?

ye sorry im dumb i got it fixed thanks
