### ISSUE TITLE
Error 0xA 

### ISSUE THREAD

**Issue by Lemaxance** [L8X/Roblox-Client-Optimizer#56]
Cant install rco because i always run as an admin my windows 10
![Capture](https://user-images.githubusercontent.com/129772342/233798533-cca6210b-2d9a-456b-8004-74a2231a8dea.PNG)
Is there a way to fix this or am i doomed ?

**Comment by Lemaxance** [comment]
Alr guys i think i found a fix , i just copied the clientappsetting.json in my roblox and it works just fine

**Comment by itsryp** [comment]
look at my post

**Comment by Lemaxance** [comment]
Well i didnt see my bad

**Comment by ivvyleague** [comment]
whats the fix? i cant see itsryp's post

**Comment by Kaiddd** [comment]
> whats the fix? i cant see itsryp's post

Have you tried every recommended fix the program tells you? If so and this still does not work, you can manually add ClientAppSettings.json to your ClientSettings folder

This will be fully resolved next update.

**Comment by Kaiddd** [comment]
Leave this open for now

**Comment by Kaiddd** [comment]
Will be fully resolved 2.1.0

In the meantime, a solution can be found in the FAQ channel of our Discord Server

https://roblox-client-optimizer.simulhost.com/discord
