### ISSUE TITLE
Roblox Install Issue?

### ISSUE THREAD

**Issue by gioprx** [L8X/Roblox-Client-Optimizer#58]
Either it's my problem or Roblox's, I've been trying to use the Roblox Client Optimizer but for some reason it says to "Please update roblox." Which I do not know how. Can anyone tell me how to solve this? It would be a pleasure.

**Comment by Kaiddd** [comment]
Expect a fix by the end of this weekend

**Comment by Kaiddd** [comment]
Closed for duplicate
