### ISSUE TITLE
Administrative Roblox Install

### ISSUE THREAD

**Issue by swooshified** [L8X/Roblox-Client-Optimizer#59]
whenever i try and install rco i get a pop-up that says detected an administrative roblox install

yet whenever i try install roblox without administrative permissions i still get the pop-up, i've even tried deleting the versions file entirely and installing roblox again but i still get the same pop-up

**Comment by Astrojox** [comment]
I had the same problem until I deleted the version file. It then prompted me with another error, 0xC.

**Comment by Nicklaus-s** [comment]
You should probably refer (and close in reference) to #54 and #51, which have been marked as bugs.

**Comment by swooshified** [comment]
> 

went thru these and i finally got it to work, thanks!
