### ISSUE TITLE
"MSVCP140.dll was not found"

### ISSUE THREAD

**Issue by spooper1** [L8X/Roblox-Client-Optimizer#60]
![image](https://user-images.githubusercontent.com/127706361/233806040-c3f9603d-2aaf-4ab2-adfe-fac9946b7721.png)
I tried installing RCO2 from the versions page, and it gives me this error. Although it says that it installed correctly, I booted up Blox Fruits and none of what was promised was there. (Edit: I did try reinstalling but that didn't help at all.)

**Comment by Kaiddd** [comment]
@spooper1 it seems you're missing the visual c redistributable, please run the installer for it in the rco installer folder, visual c redistributable is a common dependency among many c++ programs

**Comment by spooper1** [comment]
> @spooper1 it seems you're missing the visual c redistributable, please run the installer for it in the rco installer folder, visual c redistributable is a common dependency among many c++ programs

Ok I will try that

**Comment by spooper1** [comment]
> @spooper1 it seems you're missing the visual c redistributable, please run the installer for it in the rco installer folder, visual c redistributable is a common dependency among many c++ programs

Thank you it worked
