### ISSUE TITLE
Update Issue

### ISSUE THREAD

**Issue by Laqota** [L8X/Roblox-Client-Optimizer#63]
I have figured out the Update Issue. Wait for RCO developers to update for version "version-8a11605ad3eb413a" which is considered Byfron v1.

Recently Byfron released to a lot of users (not all) to test the system. You can check if you have the Byfron update by using this link. (You must be signed in to the accounts you want to test as this is the Roblox API)
https://clientsettings.roblox.com/v2/user-channel?binaryType=WindowsPlayer

**Whatever you see here. Let me tell you.**
_zwinplayer64_ - Sadly you are currently enrolled in the Byfron update (This cannot be reversed and was forced upon you) You must now wait for Byfron to hit live, or for RCO developers to allow the version listed above.
_LIVE_ - You are not enrolled in the Byfron update. If you still are hit with an update message contact RCO developers as this is their issue.

So. RCO will be out for a while or until the developers update the client for Byfron enrolled users.

**If you find the link suspicious. Here is what you can do as an alternative**

Go to your Roblox files, open up the clients version and if you see "RobloxPlayerBeta.dll" you are sadly enrolled in Byfron and is a different version than LIVE clients (RCO uses the LIVE version) so it will be broken for Byfron Enrolled users.

**Comment by Kaiddd** [comment]
Thanks. I figured this was the case...

RCO will have a hotfix tonight

**Comment by Kaiddd** [comment]
Also to any readers of above, I can vouch for https://clientsettings.roblox.com/v2/user-channel?binaryType=WindowsPlayer

That is a completely legitimate roblox api endpoint

**Comment by ItMe12sTH** [comment]
You can do a workaround for this issue by manually installing ClientAppSettings

**Comment by Kaiddd** [comment]
Fixed, pushing right now.
