### ISSUE TITLE
How do I set my FPS to a specific amount and not have it completely unlocked?

### ISSUE THREAD

**Issue by DoggoSlayz** [L8X/Roblox-Client-Optimizer#78]
So I want to set my FPS to 165 specifically, instead of the cap being unlimited. Is there currently a way to do this using RCO?

Also, apologies if this is in the wrong section. I don't know my way around github too well.

**Comment by Kaiddd** [comment]
RCO 2.1.0 will have a way to do this automatically, for now, go to %localappdata%\Roblox\Versions\current-roblox-version\ClientSettings and open up ClientAppSettings.json

Hit ctrl f to search, type fps, and modify the extremely large number to be 165
