### ISSUE TITLE
Roblox Outdated, trying again in 10 seconds

### ISSUE THREAD

**Issue by q4lbi** [L8X/Roblox-Client-Optimizer#80]
Very sorry if this is a silly issue report but considering there is no social media I can find to contact you guys, this is my best option.

After reinstalling Roblox and making sure I have the latest update which is the one from 22th of April, it appears RCO keeps saying that the Roblox version I have is outdated. Could you please tell me what I'm missing or doing wrong? Thank you.

**Comment by Kaiddd** [comment]
@q4lbi your RCO seems to be outdated, please close it via alt f4, and relaunch it via C:\RClientOptimizer2\RCO2.exe

It'll automatically open up the installer for the update for you.
