### ISSUE TITLE
RCO not detecting my client

### ISSUE THREAD

**Issue by ForgottenDebt** [L8X/Roblox-Client-Optimizer#9]
![image](https://user-images.githubusercontent.com/120201399/208287712-def2d713-3738-4098-9d96-0e85660b8760.png)

**Comment by Kaiddd** [comment]
@L8X I'll look into it later today

**Comment by Loishio** [comment]
I'm also having the same issue.

**Comment by Kaiddd** [comment]
Sorry I forgot, @L8X remind me on discord in 12 hours

**Comment by DrakeIsBruh** [comment]
I also am having trouble getting roblox to work with this.

**Comment by mogolicoo** [comment]
My only guess the root of this issue is because the program is only searching for the Roblox\Versions folder in the Local folder in AppData while being in Program Files x86 (in my case)

**Comment by Kaiddd** [comment]
@mogolicoo how'd you install roblox to the program files folder? Do you just run the installer as admin??

**Comment by Kaiddd** [comment]
Trying to resolve all past issues in 2.0.1

**Comment by mogolicoo** [comment]
@Kaiddd oops sorry for the l8 response, from what i know if you open the installer as an admin then yea it gets installed on program files, otherwise it'll install in appdata

**Comment by Kaiddd** [comment]
@mogolicoo this issue will be finally resolved in 2.0.1, thank you. If I cannot get the installation method above to work, I'll ping you again here. I'll also notify you here when I've fixed this issue.

**Comment by Kaiddd** [comment]
Fix is not possible due to user rights restrictions, but 2.0.1 will have at least a detection for this issue, as well as steps to solve this issue. Steps are uninstalling Roblox and deleting C:\Program Files (x86)\Roblox folder, and then installing the standard user version of Roblox, closing this issue, thank you for your cooperation!
