### ISSUE TITLE
I need help, i dont know what to do

### ISSUE THREAD

**Issue by XDPROAADARSH** [L8X/Roblox-Client-Optimizer#96]
(This will be fully compatible in 2.1.0) Detected an Administrative Roblox install at C:\Program Files (x86)\Roblox\Versions
Please reinstall Roblox without administrator, as RCO does not have Administrative permissions. | 0xA
If you've already reinstalled and still see this, please delete C:\Program Files (x86)\Roblox

If it still doesn't work, please verify if your 'Program Files (x86)' is set to 'Read-Only' and change it to b

someone please help

**Comment by XDPROAADARSH** [comment]
a

**Comment by Kaiddd** [comment]
Join our discord and read the faq for a fix, or wait till 2.1.0 release
